---
title: "HR Analytics Is A ‘Way of Doing HR’- Not An ‘Add-On’"
author: "Lyndon Sundmark, MBA"
date: "2020-09-01"
categories: [HR Analytics]
---

# Introduction

HR Analytics Is a different way of doing HR -period. It's not an add-on. It's typically not a single initiative, but rather a series of initiatives to change the way we do HR. That's how we should see it.

The way we see, understand, and define HR Analytics profoundly affects both our ability to implement it and to see long term success in it. If we don't see this, we are destined to put off its potential for giving us a competitive advantage for decades.

The rest of this blog article is an 'opinion' piece to try to help HR professionals understand why this is the case.

# Our Current Thinking Traps Us

So much of what is shared on the internet regarding HR Analytics these days, gives the impression that organizations who want to get into it, simply see this as an add-on to what they are currently doing - just another area of HR to implement.

Many of the answers to the question 'how do I implement HR Analytics in my organization?' often come back as:

-   you will need to get additional resources.

-   you will need to get support from the top.

-   you will need to write a business case to get those resources and that support.

This advice generally assumes that you already know

-   What you will need to do.

-   What you will 'need' in order to do what you want to do.

-   How exactly you will save money that will justify the resources needed for the change in the first place.

**You can see that the advice above pre-supposes a separate distinct initiative.**

In some organizations, you may hit it lucky in that the organization has a problem that can no longer be ignored, and the executive is ready and willing to risk some expenditure to address the problem when the actual final solution may not yet be apparent. In other organizations, you may not be as lucky and might have a much more difficult time justifying a business case for more resources to begin your journey in HR Analytics.

**To me, this sounds like a 'chicken and egg' problem.**

How do you get sufficient evidence to properly justify a business case for HR Analytics to get the resources to do it, when often that requires HR Analytics, to be present in the first place, to demonstrate how it can improve organization performance to justify the resources requested?

If all this rings a note of truth in your experiences either historically, or currently, with respect to your own effort to get HR Analytics going- there may be reasons for what you have experienced. Part of it may be due to your organizational culture, and its practices regarding resource requests, approvals, and allocations.

However, potentially a much bigger part of it may be how you are envisioning what HR Analytics is in the first place.

# Let's Get Back to Foundational Definitions

Many definitions for HR Analytics out there tend to converge on the following theme:

**"HR Analytics is 'data-driven' HR management and decision-making"**

This is a robust definition because it highlights what we are doing and how we do it. And it has much depth to be explored. Consider the following:

-   HR Analytics is all about HR Management and Decision Making. 'Hmmmmmm' -add -on? Special initiative? I don't think so. Certainly not at its 'intentional' core. It concerns itself with the domain of 'HR management and HR decision-making'

-   HR Analytics is all about being **'data-driven'** in HR management and decision making. This begs the question -- 'If it's not 'data-driven' now, what is HR management and decision making based on traditionally and currently?'

HR Analytics means:

-   going far beyond just traditional HR Metrics (although they are an important and fair-sized part of it). Metrics mean 'measurement'. It means knowing:

    -   what to measure,

    -   how to measure it,

    -   why we measure it,

    -   and exactly what can be measured.

-   going beyond just HR Dashboards. These are just a form of descriptive analytics telling you 'what is' and/or 'what has been'. Neither of those guarantees any actual analysis or subsequent action (often just armchair perusal and theorizing). Very often the immediate question after the development of a dashboard is 'So what? Now What? What do we do from here?

-   seeing ALL of HR from an informational and analytical perspective. You can't be 'data-driven' in HR without this.

When you consider all the above, perhaps the most critical message is that: \*\*"What makes us think that our HR Analytics initiatives will ever be successful and self-sustaining- if we don't fundamentally see it as a change in the way we do HR?'\*\* Sure, we can engage in a 'series' of initiatives, but without this, they could have a very short shelf/credibility life.

# How Does All This Relate to Our Efforts to Get Started in HR Analytics?

In my experience (for what it's worth),

-   Business cases are rarely the starting point for HR Analytics. This is partly due to the requirements of business cases themselves, and the assumptions inherent in them.

    -   Business cases tend to assume that you don't already have the resources necessary for what you are proposing. That's why you are writing a business case.

    -   Business cases often assume detailed knowledge of the proposed 'initiative' even before it exists. This is often not the reality if the writing of the business case is the first step in the initiative. More often they are written from whatever knowledge and facts are at hand-complete or incomplete.

    -   Business cases can often be the place where good ideas and innovation in the organization go to die rather than being given life. Too often the requirements of getting a business case written and even if it is successful, getting it through the budgeting cycle in an organization (if necessary) can take months. Initiatives which are a response to an organizational problem can often take so long for the resources to be made available, the issue may have either disappeared or have gotten 10 times worse. If the business case is in response to an emerging opportunity, the opportunity could be lost if the process for obtaining resources takes too long.

-   HR is traditionally not 'data-driven' in most areas currently or historically-its traditionally not even thought of in that way. Some notable exceptions might be in collective bargaining costing, and salary surveys and salary administration -which are by nature somewhat quantitative. So, what is much of HR driven by? Good question. Some thoughts:

    -   HR is often **'reactive, amnesic'** individual request / transaction-driven (not meant in a judgmental or critical way but rather in a descriptive way). A request for something comes in, HR acts upon it and delivers the outcome to the requestor. These could be in the form of emails, meetings, or a request for a tangible deliverable. Much of HR work, by necessity, is like this- transaction-driven. We are indeed a 'service' provider. Service Requests are much of our lifeblood. In many cases though, once the request is completed -- it's out of sight and out of mind- and on to the next request with no end it sight. In other words, often there is no memory retained after its gone. Nothing is recorded systematically. The only evidence might be emails and meeting notes which are rarely stored systematically in one place. It's like there is organizational amnesia with respect to HR services. HR often doesn't recognize that this can be an ongoing goldmine of information. **NOT DATA-DRIVEN**.

    -   HR is often professional networking/conference/vendor-driven. HR professional conferences thrive on bringing in the latest on what's cool, what's hip in terms of speakers, and usually, conferences have a myriad of HR solution vendors selling their services/products who pay to be there to help offset the cost of the event. Very often, very little attention is paid to a robust evidence-based evaluation of either the presenters or the vendor solutions. (Maybe it's just me and my experience). **NOT DATA-DRIVEN**.

    -   HR is often not measurement-driven and therefore often not innovation-driven. When you review HR practices over the decades, except for changes driven be legislative compliance, practices, and methodologies in much of HR haven't changed much.

        -   Performance Measurement is still Performance Appraisal- subjective measurement at best- even with 360-degree appraisals where the subjective is just averaged over more people. This, to me, isn't really thinking 'differently' but rather a variation on the existing theme.

        -   Job Evaluation/Classification is often still point method, factor comparison etc. Still very subjective. The length of time these have been around is a testament to not necessarily 'thinking differently'. 'Classification of items into known groups in a population' are also methodologies in statistics (predictive analytics/machine learning algorithms). Job Classification is taking an 'unknown' new job description and attempting to classify it into a known population of class specs and already classified job descriptions. With these parallel goals, why aren't these statistical tools in more evidence in HR job classification methodologies and practices? That would be thinking differently.

        -   Job descriptions are still job descriptions. Most of the time -they are still narrative. Automation is limited to simply Word documents on a file server somewhere. This is a variation on their current theme- a minor step up from the traditional paper copies. What about rethinking Job Descriptions in their entirety? Why not document the work of the entire organization then let job descriptions be subsets this work organized by individual roles within the organization- allowing for a real comparison of differences between jobs? Instead of job descriptions being individually written 'one-offs', they are documented as a part of a larger 'unified whole'. That would be an example of thinking differently in this area of HR.

    -   As you can see from the above, often very little thought is given to 'measurement' per se, in these traditional methodologies and practices. The question as to whether these could be done very differently - is rarely, if ever, asked. Enhancing by information technology, in this case, means going beyond just automating subjective processes and instead automating by data science, machine learning, and analytics). **NOT DATA-DRIVEN.**

-   HR is often thought of, by many HR Professionals, as a soft area/ a people area - **not technical.** Therefore, many people seek this profession out to avoid anything technical. The reality is "Measurement 'IS' technical" and often simply not in evidence in HR practices in many organizations. Innovation is almost impossible where there is no measurement. Without it - how does HR know that they are doing better than before when introducing new ways of doing things? Simply doing something new doesn't necessarily equate to innovation. HR remains in status quo. **NOT DATA-DRIVEN.**

You can generally see that if we see HR Analytics as a series of initiatives

-   separate from current HR functions and activities

-   ·requiring business cases for extra resources

-   and not seeing it as fundamentally changing the way we do HR as well

\- we are missing the point.

'Data-Driven' means 'information-based', 'measurement-based', and 'evidence-based' infused wherever possible into the very fabric of HR practices and methodologies. In the absence of this recognition and change:

-   We may write a successful business case and get resources for some new 'analytics' initiatives

-   We might even have HR Analytics thrust upon HR from the outside as part of a wider organizational analytics initiative.

But, at best its success will be limited in this scenario. At worst it will be just another fad we tried, unsure of what went wrong, and the status quo of 'same old, same old' will return. Innovation may be stifled, and competitors who didn't make these mistakes gain a competitive advantage on us. And this will primarily be because we haven't seen it as 'changing the way we do HR'.

# How Might We Overcome Some of The Above Challenges?

I think there is much that can be done to overcome many of these challenges

## HR

If we aren't already doing it:

-   See HR Analytics as a change in the way we do HR and not as a special separate initiative. See it as 'data-driven', 'evidence-based' HR management, and decision making. It may contain a series of 'initiatives' because we are changing the way we do HR, but those initiatives need to be seen as being core to HR methodologies and practices that re-engineer HR for the future. See these initiatives in that context.

-   'Own it!' HR Analytics is not someone else's, some other areas responsibility. Its HR's responsibility. And all of HR- not just an analytics/reporting team in HR. No one else has HR domain knowledge other than HR. Other areas such as IT and Data Scientists in the organization may be involved to support you- but its your responsibility, and your 'HR methodologies and practices 'change' initiatives'.

-   Don't assume that the initial efforts necessarily require additional resources and therefore a business case. HR Analytics at its core requires 3 things:

    -   HR Domain knowledge- which you have -- otherwise you wouldn't be working this field

    -   Rightful access to HR information -consistent with whatever your organizational data governance and government legislative requirements are.

    -   Tools to organize and analyze your data- typically statistical analysis software There are free or 'free to prototype' tools available.

When you consider the above - as the start - where do those 3 things require 'extra' resources that cost money?

-   Obtain the necessary analytical skills. HR Analytics requires HR domain knowledge, Information technology skills-at a minimum specifically data access and data organizing skills, and statistical analysis skills. It also requires you to see HR from an informational and analytical perspective. (For example, if you have an applicant tracking system- know what information it contains and how its organized) Even if you believe you can rely on other organizational areas for this in the short term, that does not equate to 'owning it' and dependency on others is often unsustainable in the long term. Infusing 'data-driven' and 'evidence-based' into HR cannot be delegated to other areas. Its your responsibility. OWN IT.

-   Wherever possible -start your initiatives with an idea and a prototype. Assuming you have the necessary skills and rightful access to data - given your HR organizational responsibilities, its far easier to enlist more organizational support when you have a working small-scale prototype created from free tools.

    -   Diagnostic analyses often reveal previously hidden valuable insights to an organization. You can do these with free tools on existing data.

    -   Predictive analyses typically start their validation by being able to take existing data and existing outcomes and developing models to see if those outcomes can be predicted- comparing the real outcomes to the predicted outcomes for how close or how often the prediction came or got it right. If the prediction is good, often the next step is to try the predictive model on data the model has not yet seen. You can do these with free tools on existing data.

Either way, you are showing by concrete 'simple' examples what might be possible with further effort. If business cases are then required for additional resources for moving forward, it's a whole lot easier to make that case.

-   Become 'measurement' driven. Data-driven requires 'data'. Measurement, at its most fundamental meaning is both the capturing of data, and the summarizing of it for either answering questions or to bring organizational visibility to things that may be of consequence. Within the context of HR this may often mean:

    -   Developing traditional HR metrics and dashboards to understand what is going in the interactions between applicants, employees and terminates in your organization -the life cycle of employees.

    -   Measuring the activity in HR and the demands put upon you. This is often best achieved through HR Service Request Tracking Systems. Most of what you do and are working on in HR is a request from someone- a 'service' request. As an HR professional you provide services. Service Request Tracking (ticketing) Systems track 'these' requests. They often record when they came in, and often record when you started it and when you completed it. By the nature of what they are, they then also capture the volume of requests that are coming in, what their current status is, and who it was assigned to. This allows for being able to measure how long typical services will take which in turn can allow for better setting of customer expectations. It also allows for better resource utilization and a way of measuring whether we are doing better over time. Without systems like this, it's almost impossible to provide yourself in HR and the organization a clear picture of the work going on in HR and its volume.

    -   Measuring how good your HR business process or practices/methodologies and techniques are with an eye for improvement in reliability and timeliness of their end results.

I can't underscore enough the consequences of not being 'data-driven' in the nature of HR work and how we do it. As mentioned earlier, my own experience over 30 years in HR had me conclude that much of HR work in organizations is 'reactive'. Much of the work is waiting for requests from the organization for something and then acting on it. It gets completed and the result given to the requestor. Once done, unless there was an issue, it's out of sight and out of mind because a new request is demanding our time.

Businesses in general, usually put a premium on getting information about their customers and their needs for repeat sales and business. If they operate totally reactive and with organizational 'amnesia' with respect to customers, they usually don't stay in business too long.

## Executives

If you aren't already doing it:

-   Similar to HR, see HR Analytics as a change in the way HR is done- requiring wherever possible that 'data-driven' be infused into the organization's HR practices and policies.

-   Recognize that HR Analytics isn't a one-time single initiative and recognize that this isn't short term either. Recognize that this may be a culture change itself in HR, so a long-term commitment and accountability may be required. Make this part of the role, responsibilities and goals of the Chief Human Resources Officer or Executive in your organization.

-   Recognize that HR changing the way it does HR will take time and that it may consist of many initiatives. Each one when complete- moves HR and the organization further- on the journey towards data-driven HR. Some of these initiatives will be able to be done within existing resources, others will require additional resources.

-   Support HR in providing you with an ongoing picture of what is happening with respect to your employees /people resources/ human resources through provision of traditional HR Metrics. Give them the resources to do this on an ongoing basis and in an automated way- so that most of the time spent is on analysis of what's going on, not in the preparation of these.

-   Support HR in encouraging the usage of Service Request Tracking Systems, so that they can give you a 'true' picture of the volume of work and demands that are put on HR on an ongoing basis

-   Set an expectation of, and provide the climate for, innovation in HR practices and methodologies and as much as possible within organizational resources and business priorities. Data Science as applied to HR practices and issues could have much potential for providing you with a competitive advantage.

## Colleges, Universities, and Other Institutions of Learning

You may have much work ahead of you since you are the educators of new HR professionals and skills upgrading for existing HR professionals.

If you aren't already doing it:

-   Include statistical analysis, data science, and information technology courses as part of core requirements in the curriculum for HR academic and professional education. This has to go beyond a statistics elective from a different faculty on campus. If the goal is to infuse analytics into the very fabric of HR work, the textbooks, the course materials and the examples themselves must be HR examples. Although I say this in the context of HR, it is equally applicable to most areas of business study. These should include:

    -   Basic statistical measures and concepts

    -   Univariate, bivariate, and multivariate statistical analyses

    -   Machine learning algorithms

    -   The Data Science process

    -   Data Mining

    -   Statistical software such as R and possibly also Python (at least the data manipulation and machine learning parts)

    -   Data cleansing, organization, and engineering

-   In addition to the above focus, require that the teaching of ALL HR courses in all HR functional areas include sections on how that function in HR is understood and represented 'process-wise and informationally':

```         
-   What is a typical business process or processes for this function?

-   What are the process information inputs, in process data, and process output data?

-   What data elements are needed and typically kept and why Where this information is generally found in an HR information system.
```

This is how to infuse HR analytics into the very fabric of how HR is done. As mentioned earlier, too much of the traditional course materials, books, and authors have not covered this. They often haven't treated HR from an additional 'process orientation', but rather as a series of functions and the concepts and traditional methodologies that go along with that. And they often don't treat HR domain knowledge from an informational and analytical perspective.

# Conclusion

I often hear the reality that 'HR doesn't have a seat at the Executive Table'.

When and where this happens is unfortunate. The HR picture of the organization is every bit as important as the financial and sales pictures to the organization. Who else but HR provides the 'HR picture'?

But to provide the HR picture, HR must be as 'data-aware' and 'data-functional' as all other areas of the business. Accounting and Finance / Sales and Marketing - they bring data and analysis. They are data-driven.

HR? Do we remain in past practices, or do we move into an innovative future? It's a critical choice.

This is why 'how' exactly we define HR Analytics, and operationalize it, is so important.
