---
title: "Announcing “Doing HR Analytics – A Practitioner’s Handbook With R Examples"
author: "Lyndon Sundmark, MBA"
date: "2017-09-06"
categories: [HR Analytics]
---

For those of you who have been following my HR analytics blog articles to date -thank you! Your interest has been appreciated. These articles have been written with the intent of encouraging 'data-driven' HR management and decision making within organizations.

As a result of the feedback from those articles, as well as feedback from some local presentations, I decided to write an e-book on the subject over the late spring and summer 2017:

"Doing HR Analytics -- A Practitioner's Handbook With R Examples"

It is available from Analytics in HR at

~~https://www.analyticsinhr.com/hr-analytics-books/~~

changed after first year to Amazon

<https://www.amazon.ca/Doing-HR-Analytics-Practitioners-Handbook-ebook/dp/B07JGGD8M7/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1704922909&sr=8-1>

Most of the books that have been written in this field talk about the significance and strategic impact of People / HR Analytics to organizations. This is important still -because very few organizations yet have a firm grasp on the competitive advantage such activity can bring. However, I think it's exceedingly important that organizations also move from the 'talking about it' to the 'hands-on doing of it'. It has been that spirit behind many of the blog articles I have written. So too with this book.

The book covers:

-   Basic concepts

-   A possible scope and breadth

-   Seeing HR from an informational and analytical perspective

-   Data Science tools

-   A Data Science framework

-   'Hands on' HR examples

-   Suggestions for how you start

The first five of the bullet points above are geared towards helping to structure your thinking and efforts. The HR examples draw on a number that I have shared in my previous blog articles, but with some minor tweaks to the code (datasets and code are included with e-book). The final bullet point attempts to address the 'where you do go from here?' question.

The book is intended for 3 audiences because skills are required from each of these in a typical People /HR Analytics effort:

-   HR Professionals- to get a better understanding of the informational side of discipline and why both IT and Data Science/ Statistics are important for successful HR analytics efforts

-   IT Professionals- in general to get a much better understanding the HR context, and help them realize that metrics and data warehousing is only part of the analytics picture.

-   Data Science Professionals- to understand that HR, like sales and marketing, is another content area of business needing Data Science as a support to it to move towards 'data-driven' and that IT is an important partner in that.

Two thoughts go a long way to understanding People / HR Analytics:

-   it's what happens when you are 'data-driven' in HR management and decision-making.

-   it's what happens when you apply Data Science and Statistics to the HR field and the HR information that is generated by organizations.

It is my hope that content of this book will aid in that understanding

Regards...
