---
title: "Is it Time To Take Another Look at How to Calculate Employee Turnover?"
author: "Lyndon Sundmark, MBA"
date: "2014-11-25"
categories: [HR Analytics]
---
::: {.callout-note appearance="simple"}
*TL;DR; In a word- YES. Current formulas for calculating turnover often use denominators which are an average. These averages really are attempting to indirectly combine inflows with the outflows. In my opinion inflow rates and outflow rates are separate entities*
:::


# Introduction

Employee turnover is a very common HR metric of interest to many organizations.

One of the things I have found, over the years, in HR metrics related projects - is that clarity, definitiveness, and consistency of definitions are all strong ingredients to usable HR metrics. HR 'metrics' are of course measures. And for measures to be useful they must be 'valid' and 'reliable'. 'Valid' means that they measure what they are supposed to measure. 'Reliable' means that it does it consistently. Take away clarity, consistency etc. and metrics lose their utility.

Recently I decided to do a quick Google search on how employee turnover was defined and how to calculate it. Admittedly this isn't overly scientific or deep. And it wasn't intended to be. But I was interested in seeing how consistent the recommended definitions and suggested formulas for calculating turnover were.

The good news was that there seemed to be relatively common definitions for turnover and for formulas as to how to calculate it.

The bad news was that even though the formula itself was relatively common- how to calculate portions of that formula were not.

What exactly did I find? Consider the following definition and formula:

Definition

Generally the definitions from the traditional typical dictionaries (Merriam Webster, Cambridge, and Oxford) centered on something like the following:

Turnover is the rate at which people leave a company.

A rate, in turn, is generally concerned with the frequency or speed of something. Often it is expressed over the measurement of time. We are not only concerned with how many people leave an organization, but over what period of time.

And for context it is often of less concern what the absolute number of people were that left but really what proportion of people left the organization out of the total number of people in the organization. So really what we are concerned with is the proportion in any given time period.

Formula

Given the above definition, it is not surprising that a common formula for turnover was:

Employee Turnover = the number of people who left the organization / the number of employees

What's implied in this formula is that it still must be within the context of 'time' to have any meaning. It's the number of employees who left over a period of time. So the formula is relatively consistent with the definition.

What was not common in the Google search was how to calculate the number of employees.

I came across at least 3 unique (non-repeating) suggestions for the denominator in my Google search:

The 'average' number of employees for the time period The number of employees at the end of the time period The number of employees at the beginning of the time period The 'average' in first suggestion above was calculated by taking the opening and closing balance for the time period in question (often a month), and dividing by 2.

As mentioned previously, for any of you who have been charged with responsibility of providing HR metrics in your organization - having absolute clarity and consistency in your definitions (turnover or any HR metric) is essential if you are going to provide meaningful HR metrics information. In fact when getting into an organization project of creating HR metrics, often the time take to define them and determining formulas for them and getting agreement on these can take as long as the technical development of these in a data warehouse itself.

If a basic Google search indicates that there are at least 3 possible ways of calculating the denominator, that doesn't exactly provide 'desired' consistency. And if different organizations make different choices as to how to calculate number of employees, you can probably appreciate the danger of asking another organization the question of 'what is their employee turnover rate?' without also asking them 'how exactly do you calculate that?' As importantly, for our own metrics and calculations- we have to also ask --'how exactly do we calculate that?' Given the options, how do we choose?

As I try to answer that question, I have no intent or desire of 'absolving' you from the responsibility of making your own choice. How you calculate it is based on your needs in your organization. Sometimes your choice will be based on regulatory requirements. Sometimes the choice is open for you. Sometimes it's both- if you consider having more than one metric for turnover. What I do desire to do is to assist you in understanding further what you are really measuring, given these 3 choices, and perhaps suggest some criteria for your choice, when the choice is not regulatory. Let's look at each of the calculation options further:

# Turnover Calculations Based On an Average for the Denominator

Employee Turnover = the number of people who left the organization /Number of Employees (Average)

The idea behind taking an 'average' is that for the time period of concern --the denominator may change. Even in an often typical smallest time period of interest for HR metrics- a 'month'- if people leave and come into the organization, 'number of people' is not constant for the whole month. Indeed, typically the following is the case for any given time period:

Average Employee Count= (Opening Count of Employees for the Period + Ending Count of Employees for the Period) /2

The argument here is that since the number of employees is not constant during the month- we can or should 'negate' the variation by taking an average employee count. The same principle would apply whether we are dealing with month, quarter, or years as the time period under consideration. On the surface this has an appealing logic. Since the count of employees will change during the period of time in question- we feel this would be a more 'representative' figure for the time period in question.

But let's dig a little deeper. 'What exactly are we measuring and what do we really have when we calculate an average for the denominator?'

We definitely have an 'arithmetic' construct- the average. But for this metric we also have the inclusion of hiring information and termination information in the denominator. Why? Because to get the ending balance for a time period (in the formula above), we must base it on the opening balance and then the changes during the time period. The changes to an employee population in any time period are reflected in the hires AND terminates within that same time period.

Ending Balance= Opening Balance -- Terminates + Hires

205= 200-25+30

Since the ending balance for that time period is part of the denominator, it means we have hires count and terminates count in the denominator for turnover. ( Per the above formula for average employee count)

Average Employee Count= (opening count + (opening count -- terminates + hires))/2

And it means that the turnover calculation using an average of opening and closing balances is really comparing the count of terminates for the period over both the original balance and the changes (hires and terminates) for that time period. Aside from hires now being introduced into the denominator, we are actually also negating terminates from the opening balance in the denominator.

So if it weren't for the 'hires' being included, terminates are not based on just the opening balance but rather the opening balance less the terminates. And then this averaged with the opening balance of the denominator too. This hardly makes sense to me personally. Especially if we consider a scenario where there were no hires in the time period. Your equation for the denominator then becomes:

(Opening balance + (opening balance- terminates+hires))/2

Example denominator: (200 + (200-25+0))/2

You are taking the opening balance of 200 above and adding that number again and subtracting the terminates of 25). Then you are dividing that by 2 to get an average. And THEN you put the numerator of the number of terminates over that. Let's see- turnover in this calculation means that we are dividing the number of those who terminated by an average of something that includes the hires and also negates the terminates in the denominator as well. Confused? I AM.

Arithmetic construct? Yes. Justifiable logic as to meaningfulness of the denominator? What do you think?

# Turnover Calculations Based on the End of the Period Count of Employees for Denominator

This approach for calculating the contents of the denominator suffers from many of the same issues as the previous suggestion. The only thing that is better here is that at least it's not an average for the sake of having an average.

Ending balance always is the opening balance minus the terminates plus the hires for a time period.

Let's look again what happens if there were no hires in a given time period for a closing balance.

(Opening balance -- terminates + hires)

Example denominator: (200-25+0)

So once again you have hires in a turnover (terminates) calculation. And if there were no hires in that time period your turnover formula is really doing a calculation of terminates over the opening balance minus those terminates. You are actually basing your terminates over a denominator that has already been reduced by the terminates.

Example turnover: 25/ (200-25+0)

Does this make sense?

# Turnover Calculations Based on the Beginning of the Period Count of Employees

The previous two options for denominator introduce the 'terminates' and the 'hires' in the denominator. It's like double counting the impact of the 'terminates' and adding 'hires' into a calculation that should be about 'terminates'. Can this be avoided? Yes -- if we agree that hires have nothing to do with turnover and that terminates have no place in the denominator either- because it is double counting. How? By having the count of employees based the opening or beginning balance of the employee count for the time period.

Why is this the case?

First of all let's look more closely at what an opening count is. An opening count in this case means the count of something before anything else can occur that would change it. What could change it? Hires and terminates for the current period. For time purposes, a new time period is often demarcated by midnight. Any transactions recorded before midnight are categorized to be the previous time period, any at or after are categorized into the current time period. This is true whether the time period is a day, month, quarter, semester, or year --when we are at the end of any of these. It also might be useful to think in terms of:

Opening Balance of Current Time Period = Closing Balance for previous time period.

The closing balance for the previous time period would be just before midnight where no other transactions logged could be possible either by time itself or by organizational intention and design.

If the terminates occur anywhere in the present time period, they must be compared or based against the previous period's closing balance/current period opening balance to NOT be double counted in the formula.

If we can see how this makes sense on a day by day time period calculation, we can understand that when we are concerned with longer time period like a month, the last 'month' population that the terminates belonged to is not the current month (end of this month) but rather were part of the previous months employee population. By definition, they are terminates in the 'current' time period. So quite aside from the interaction of terminates and hires in the denominator with the previous two options, this option makes sense intuitively even without that interaction impact.

# Final Thoughts

As mentioned earlier- every organization has to make its own decision as to how it will calculate turnover (and the number of employees in the denominator). Sometimes the decision is made for you because it is a regulatory requirement for some purpose. Other times it is not.

None of the discussion in this article is here to suggest or imply that you as the reader need to change your current definitions or calculations. That's really your decision and responsibility based on your needs.

But perhaps I can leave you with some closing thoughts or suggested criteria for your choice, whether it be for regulatory or other purposes:

Is there a reasoning behind why you are calculating it the way you are calculating it? If a regulatory reason requires one of the above 3 choices in your denominator, then that is reason enough for 'that' purpose. Can you have multiple turnover measures for different purposes? Some may be for regulatory purposes, some for benchmarking with other organizations. These may require different calculations. If the purpose for the calculation is for comparison to other organizations, how do they calculate the denominator? Is their entire formula the same? If so, your purposes are met. If not, another formula may be required for that specific purpose or intent. If there is no regulatory required definition for your employee turnover metric, does your metric really measure what you think it measures? And if you have more than one calculation for turnover, are your definitions and terminology allowing you to distinguish between them and still have clarity, meaningful dialogue, and a reaching of all the purposes intended? What do you think?

::: {.callout-note appearance="simple"}
About Lyndon Sundmark, MBA

Lyndon is a retired HR Professional with over 40 years experience of applying a 'data-driven', 'evidence based' mindset to HR practices in organizations in a variety of roles and industries.
:::
