---
title: "Workforce/HR/People Analytics- Is This a Wake-Up Call for HR?"
author: "Lyndon Sundmark, MBA"
categories: [HR Analytics]
date: "2014-12-17"
---

# Workforce/HR/People Analytics- Is This a Wake-Up Call for HR?

## Introduction

Over the last 35 years or so, I have had the privilege of working jointly in the HR and IT fields and in the interaction of those fields over that time period. Coupled with the foregoing has been an interest and a passion for human resources, information technology, and statistics- applying statistical analysis to HR data.

The combination of these experiences has enabled me to witness many changes in each of the above areas over that period of time. HR practices have increased in robustness and variety. Application of technology to the HR function has changed dramatically. This includes having:

-   very powerful HR information systems that support the bulk of the transactional activity that HR engages in in most areas/functions of HR

-   usage of word processing, spreadsheet, presentation, and social media software at the individual user level in HR to increase their productivity at the individual level

-   the preparation of HR Metrics (in some organizations)- sometimes for internal Executive reporting purposes, and sometimes for external benchmarking purposes.

In spite of all the above changes, the one thing I have not seen as much of ##is robust statistical analysis of HR data for decision making purposes##. That's not saying use of statistical analysis on HR data hasn't existed. The areas most likely to have made some use of some statistical analysis -- is probably the Labor/Industrial Relations area for collective bargaining purposes, Human Resource Forecasting, and perhaps Salary Administration/Job Classification for salary survey etc. type of purposes.

But for much of HR decisions and practices in organizations, the decisions have often been far more subjective than they needed to be, and many aspects of those HR practices at their 'essence' have not changed over the last 35 years even if some of the tools have. To some HR practitioners, they see HR as a 'soft', 'people', 'non-technical' type of work.

While as compared to other staff areas such as Finance, Supply Chain, and Legal etc.- HR is perhaps more 'people related' because HR concerns itself with the organizational people related issues- this view of HR as a 'soft' area is incomplete. HR has also always been very analytical and technical. On a personal level, I have always believed that statistical analysis of HR data and its application in HR decision making had the potential for a much wider application in HR practices

I recently came across an article that seems to support the above belief titled 'How Google is Using People Analytics to Completely Reinvent HR

[<u>http://www.tlnt.com/2013/02/26/how-google-is-using-people-analytics-to-completely-reinvent-hr/</u>](http://www.tlnt.com/2013/02/26/how-google-is-using-people-analytics-to-completely-reinvent-hr/)

The article profiles Google as a company with respect to some of its People practices and the role of 'People Analytics' in those practices. While the article uses the term 'people' analytics, if you have 'googled' on analytics related to HR, you will likely notice that other terms will also come up including workforce analytics and HR analytics.

While I encourage a read of the above noted article directly, I wanted to synthesize from this and some other sources googled from the internet in order to provide a bit wider picture of analytics as it applies to Human Resources and why I think it \*\* is a 'wakeup call' for HR \*\*.

## What Exactly Is Workforce/HR/People Analytics?

One of the things that is often the case in 'leading', 'bleeding' edges of any field is that terminology is often still in flux and working itself out in terms of meaning for a period of time.

As I started to do some review of the terminology, I found a variety of definitions for Workforce Analytics, HR Analytics, and People Analytics. These definitions all seemed to try cover similar ground albeit sometimes with some minor differences in nuance. At the present point in time, I see them as synonymous in terms of intent- but someone out there could correct me on that.

Let's take a look at some of these definitions first and then consider their similarities. The definitions below are intended to be illustrative not exhaustive.

**Workforce Analytics**

*From* [<u>http://www.gartner.com/it-glossary/workforce-analytics</u>](http://www.gartner.com/it-glossary/workforce-analytics)

\##*"Workforce analytics## is an advanced set of data analysis tools and metrics for comprehensive workforce performance measurement and improvement. It analyzes recruitment, staffing, training and development, personnel, and compensation and benefits, as well as standard ratios that consist of time to fill, cost per hire, accession rate, retention rate, add rate, replacement rate, time to start and offer acceptance rate."*

**HR Analytics**

*From* [<u>http://www.techopedia.com/definition/28334/human-resources-analytics-hr-analytics</u>](http://www.techopedia.com/definition/28334/human-resources-analytics-hr-analytics)

*Human resource analytics (HR analytics) is an area in the field of analytics that refers to applying analytic processes to the human resource department of an organization in the hope of improving employee performance and therefore getting a better return on investment. HR analytics does not just deal with gathering data on employee efficiency. Instead, it aims to provide insight into each process by gathering data and then using it to make relevant decisions about how to improve these processes.*

\*What HR analytics does is correlate business data and people data, which can help establish important connections later on. The key aspect of HR analytics is to conclusively show the impact the HR department has on the organization as a whole. Establishing a cause-and-effect relationship between what HR does and business outcomes - and then creating strategies based on that information - is what HR analytics is all about.

HR has core functions that can be enhanced by applying processes in analytics. These are acquisition, optimization, paying and developing the workforce of the organization. HR analytics can help to dig problems and issues surrounding these requirements and using analytical workflow will guide the managers to answer questions and gain insights from information at hand, then make relevant decisions and take appropriate actions."\*

***People Analytics***

*From Dr. Sullivan's article:* [<u>http://www.tlnt.com/2013/02/26/how-google-is-using-people-analytics-to-completely-reinvent-hr/</u>](http://www.tlnt.com/2013/02/26/how-google-is-using-people-analytics-to-completely-reinvent-hr/)

*"##People analytics## is a data-driven approach to managing people at work. Those working in people analytics strive to bring data and sophisticated analysis to bear on people-related issues, such as recruiting, performance evaluation, leadership, hiring and promotion, job and team design, and compensation ...*

*It is just listening to what your data says about you in the area of human resources. Data says a lot about how to run a company, and people analytics isn't as scary as it sounds. It is really just the continuation of current trends in management, supporting them with data and informing action by insights derived from the data. It simply requires decisions to be supported by data, which is what we ask of most decision makers in a company already...*

*The basic premise of the "people analytics" approach is that accurate people management decisions are the most important and impactful decisions that a firm can make. You simply can't produce superior business results unless your managers are making accurate people management decisions."*

## What Can We Glean From These Definitions?

As one looks over these definitions a number of similarities emerge which I think get at the heart of what analytics are and why they are important:

-   **Workforce/HR/People analytics are a 'data driven' approach to managing people at work.** What would be implied in this is that it isn't data just for the sake of data, but data for a purpose. It implies that when you make HR decisions, you need to be able to show from your own internal research and data, why you are taking the actions you do

-   **The scope of a 'data driven' approach covers ALL HR functions and practices.** The potential of Analytics to 'reinvent' HR can impact everything. The scope is not just HR Department improvement but organizational improvement through the correlation of HR data to business data. It is about what we do, how we do it, and what impact that is really having on the organization.

-   **'Data driven' implies 'data'. It may seem trite to say that, but to have 'data' means that we are measuring.** This typically means metrics -- not just transactional metrics but performance metrics as well. (not just what are we doing , but how well we are doing it)

-   **Analytics and metrics aren't just about HR data but are also about their tie to business data**. It's not just about HR Department improvement but organizational improvement through the correlation of HR data to business data. It is about what we do, how we do it, and what impact we are really having on the organization, as HR professionals.

-   **Analytics are not just armchair empiricism, but rather the application of statistical analysis tools to HR data and metrics**. It goes beyond a sense or a gut feel. At best a gut feel or sense is a 'hypothesis' that should be subject to confirmation by data.

-   **The 'purpose' of analytics is for performance improvement whether at individual. HR Department/Operations or at the organizational/business outcome level**. This means more accurate, more proactive (predictive) and less reactive decisions, quicker and more productive and efficient HR decisions.

-   **In statistical terms, the scope of analytics could cover prediction, correlation, and process quality improvement tools and possibly other areas as well.**

## Why Might This Be a Wake-Up Call for HR?

If Workforce/HR/People analytics truly have the potential to both reinvent and transform HR practices and business outcomes, the wakeup call might end up being the impact of HR and the organization not benefiting from that potential.

Consider the following:

-   **Your own performance as an HR department and as an organization may be limited** - comment provided in the Google people practices article above :

-   '*The basic premise of the "people analytics" approach is that accurate people management decisions are the most important and impactful decisions that a firm can make. You simply can't produce superior business results unless your managers are making accurate people management decision'*

If you aren't collecting the data, measuring, and doing the analysis -- how do you know you are producing superior results?

-   **Your own competitiveness may suffer.** One of the more annoying trends impacting HR these days, for some, is the 'justifying your existence' as HR in your organization. Annoying particularly because it often feels like an organization thinks it can get along without HR and HR practices. In reality of course it can't (any more than it can do without finance and accounting etc.).But ##the reality may be that it can get its HR activity done without 'You'##. Are 'You' doing it better than the alternatives (contracting it out, reorganizing to create' shared services organizations', etc.)? Do you know? How do you know? I suppose the only thing worse that 'justifying your existence' is not even being given the opportunity to 'justify your existence' before restructuring decisions contract it out. If part of the picture of People analytics is HR process improvement analyses, and as an organization this isn't built into being part of your HR operations, it would be difficult to show your competitiveness. This isn't just an issue for HR but all organizational operations. Some organizations have the view that if you are not in direct delivery of the organization's overall product or service -- you are not part of the core business- as if organizations could operate without organizational infrastructure that keeps the organization operating smoothly. The other mistake I think organizations make here is that they may demand 'justify your existence' without those who are demanding having any data to prove that the alternatives are any better either. The point is HR significantly helps its circumstances when it knows and can show its internal competitiveness through metrics and show it compares to other organizations by benchmarking. And proactively doing this, ahead of an executive 'ask'.

-   **The means to have a 'data driven' approach isn't new**- but the execution of it and visibility of it is likely more recent. The basics to have 'data driven' HR: the HR function and practices, the ability to create and store data, the existence of statistical packages for analysis has been around for over 35 years in some form. The willingness to recognize this and have it become part of the DNA of what we do in HR and how we do it is what is new. This is probably an area of HR that has needed recognition for quite some time. The above Google People practices described are one example of this and its recency.

-   **The current provision and use of HR metrics where it does exist and occur can sometimes be 'insufficient'.** I am a strong believer in the **provision** AND **use of** metrics. But insufficiencies can exist in both provision and use. In fact sometimes the provision affects the use.

-   **The technology exists and is used in many organizations to create the HR metrics -- data warehousing and business intelligence tools.** Dashboards are created. And yet often the data is simply reviewed and no targeted action taken. Sometimes it's because the metrics are not generated in a way that allows for the slicing and dicing and further analysis ##inside ##the organization. When that happens, there is no means to analyze the problem internally and take some targeted 'data driven' action. We get the use for 'benchmarking' (external use) right-comparison to other organizations, but we don't get the internal picture right.

-   Being able to 'take action' implies that you are able to 'interact' with your data. There are many powerful visual tools that are emerging for use in data analysis and slicing and dicing in real time on your metrics. This interaction is often critical for 'what if' types of questions and analyses. However, where there can sometimes be an insufficiency here is knowing **'what to pay attention to' in the data.** Part of what to pay attention to is based on what questions you are asking. But part of it is also using statistics, statistical tools and statistical analysis to determine what is statistically significant. This is important because we can create and process so much data that it can be easy to drown in it. And if we drown in it, it's unlikely we will be able take targeted action as well.

There may be other reasons for this being appropriately perceived as a wake-up call as well. The above are just a few thoughts that come to mind.

## How Might HR Respond To This?

I suppose part of the answer to this question is based on whether you accept the premise that the Google People Practices are based on and that you want a 'data driven' approach to managing people at work:

*The basic premise of the "people analytics" approach is that accurate people management decisions are the most important and impactful decisions that a firm can make. You simply can't produce superior business results unless your managers are making accurate people management decisions."*

If you don't agree with the premise and that you don't see the need for managing people in organizations as needing to be data driven, it's unlikely you will see this as a wakeup call and feel a need to respond. Ultimately that is every organization's and HR practitioner's decision and choice.

If you do decide that this is relevant to you personally as an HR practitioner or as an HR function in an organization, or as an organization in general, then I think there are many things that are conducive to moving in the direction of leveraging analytics to make 'data driven' people management decisions.

Here are some thoughts:

-   **Start reading, researching and staying on top of developments in this area.** Understand how this might apply to your specific specialty with in HR if you are a practitioner. Understand how this might apply to your operations if you are an HR leader. Be aware that much of the terminology and ideas are still in flux- and grow as the discipline grows. My own personal sense is that this is still a 'leading', 'bleeding' edge of HR activity and practice. As such, the definitions and practices are likely to be in flux and evolve over a period of time. What impresses me about the Google example above, is that it is refreshing, exciting and challenging. It is a real life example of actually bringing visibility to 'data driven' people decisions. Google will eventually be ##one## ##of a number of examples## as more organizations see the potential and start taking steps in a 'data driven' people management direction.

-   **Take claim to HR analytics as part of the HR domain**. This isn't a situation of 'no' decision being made. You make a decision either way- to either see HR analytics as part of HR and taking ownership and control of it, or have the risk of someone else taking ownership of it at some point. (That may or may not be HR). Some organizations make an argument it should be in a Finance area. I personally find that ludicrous. Finance often knows no more about the context of HR than HR does of Finance. Ownership should be in the area that has the domain knowledge. Organizational politics sometimes dictate otherwise. Take claim regardless of where you are in implementation or robustness.

-   **See Workforce/HR/People Analytics simultaneously as both a separate discipline within HR and also as a core HR knowledge requirement at a basic level for all of HR.** Some portions of this might require extensive separate knowledge by a specialized group in HR, and yet at the same some parts require a base understanding by all HR practitioners of what it is, why it is important, and a general sense of how it could/should be operationalized in your specific discipline within HR.

-   **See your 'hands on' use of the technology to do this as both an extension of who you are as an HR professional and as a tool for increasing your competitiveness.** Understand that because it is data driven, the hands on use of technology in HR is not optional but rather a requirement. Data driven means interaction with and exploring your data. In seeing HR and IT evolve over the last 3 decades, I have come across many situations where some HR practitioners have seen HR as non-technical, non-quantitative, non-data related. Or in some cases, even when they see the 'data' aspects of it, they think if it involves data it's a non-professional or non-managerial function. I believe this is a wrong view of data and technology. As an HR practitioner at any level, understand that your competitiveness is partly a function of applying technology wherever you can effectively to do what you do better in HR. If you want HR to move into being data driven- technology needs to have hands on use.

-   **Be smart in your use (or not) of prepackaged vendor analytics software solutions.** Don't assume that if your current HRIS package has an 'analytics' feature, that that necessarily is valuable or means anything. Depending on what is provided it may or may not. The concern with 'pre-packaged' solutions is that they by their nature presume to know the data driven people decisions that exist and the questions that need to be asked. That may not necessarily be the case. Hands on interaction with your data through statistical tools, with your knowledge of your business and HR issues is much closer to the intent of Workforce/HR/People Analytics.

-   **Increase your knowledge of statistics and statistical analysis.** Understand that to extent that analytics often makes use of and needs to make use of advanced analytical tools, this typically implies statistical tools and statistical analysis. This in turn implies that you have an understanding of statistics and the how to use statistical tools and programs to do advanced analysis. One of the difficulties, I saw over many years is that in business diplomas and degrees, if statistics was taught as part of the curriculum at all, it was usually an elective taught by a science faculty. Often then, the examples how statistical analysis could be used in a relevant way were sketchy at best, because the examples were often directly scientific. For me personally, I did not understand the relevancy of statistics and statistical analysis until it was taught as applied 'Business' statistical analysis. Then the applicability of it for use in solving business problems became visible for the first time. 'Context' is everything. Statistical analysis is not only relevant but imperative in improving how we do what we do in HR. As HR practitioners, if you don't already have a background in statistics and the use of statistical packages, this is critical to having People Management decisions being conducive to being data driven. Access to statistical packages these days is no obstacle. The R statistics software package on the internet is ##free##, and is available for installation on Windows, Macintosh and Linux operating systems.

-   **Possibly change your paradigm of HR**. For many HR practitioners, HR is often seen as strictly the set of practices and methodologies used in HR that form the HR function in an organization (a series of silos and a top down orientation). In that paradigm, practices and methodologies are what they are irrespective to any connection to organizational outcomes, and they don't have to be justified. You often see examples of this on blogs and discussion groups where the merit of a particular approach is touted -- but it is done without any discussion of its use being tied to evidence on wider organizational outcomes. What may need to change for some organizations is seeing the entirety of HR in a service process model paradigm. One way of understanding this is to put the 'vertical' silos of HR on their side horizontally. If we borrow from the quality improvement world, think of SIPOC ( Suppliers- Inputs-Process-Outputs-Customers) See the entirety of HR silos as really the provision of 'services' to customers. To the right are customers. Those customers have expectations of the outputs (services). Those services have processes that exist that allow the services to be provided. The processes in turn have inputs. These would be to the left. The inputs in turn come from suppliers. The processes may or may not be working well. They may not be producing quality service output. The efficacy of any specific HR approach, practice, or methodology is also partly a function of the degree to which organizational performance is enhanced by its use (customers more satisfied with services provided). We then cannot talk about the merits of one approach over another, without also tying it to organizational outcomes. Data driven? --YES.

## Final Thoughts

As I have suggested in the above, I believe Workforce/ HR/ People analytics are still in their early stages of use and terminology in HR. Even with that being the case, what is at the heart of the use and terminology for this is 'data driven' decision making. 'Data driven' goes beyond simply producing metrics. It is:

-   Being able to take a HR issue or question, understand what data exists around and available for that decision, understand what statistical analyses or summaries are useful to answer that question, presenting that data as part of the decision and decision making process
-   Understanding for our existing metrics, why we produce them in the first place and what questions they were intended to answer.
-   Being able to take overall metrics, measures, and data and be able to slice and dice understand underlying relationships.
-   Making a decision as HR professionals to be 'data driven'. As I mentioned earlier in this article, the ability to generate datasets of HR data and availability of applying statistical tools has been around for at least 35 years. The technologies have changed and have become more robust, and the amount and scope of data has increased over that period of time. The tools and data needed to do this are not necessarily an obstacle.

Google is indeed doing some tremendously exciting things in their People practices. They have taken the bold move to increase dramatically their ability to be 'data driven' in their HR practices. And they will likely continue to see payoffs for their decisions.

I guess the key question is- how will Workforce, HR, People Analytics impact you and your organization?
